dbt_sales_db:
  outputs:
    dev:
      catalog: sales_dev
      host: dbc-2ea47e01-b9ad.cloud.databricks.com
      http_path: /sql/1.0/warehouses/60d2f96239fe8610
      schema: default
      threads: 6
      token: dapia8e776a69dbd512432eddcd75e457343
      type: databricks
  target: dev
